name: qc

on:
  workflow_dispatch:
  push:
    paths:
      - '*.py'
      - '**.py'

jobs:
  check-flake:
    name: run "nix flake check"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check
