name: qc

on:
  workflow_dispatch:
  push:
    paths:
      - '*.py'
      - '**.py'

jobs:
  check-flake:
    name: 'check nix flake (nix flake check)'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check

  tomlantic-tests:
    name: 'run tests on tomlantic (nix run .#tests)'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix run .#tests

  tomlantic-lint:
    name: 'run linters on tomlantic (nix run .#lint)'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix run .#lint
